#!/usr/bin/env bash
# Tool-adoption evidence lane.
#
# jankurai replaces a fleet of ad-hoc tools (manual scoring, gitleaks-only
# security, hand-rolled coverage/contract drift checks) with first-class
# subcommands. This lane runs each adopted command in CI and writes its
# evidence artifact under target/jankurai/ so the audit can prove the
# replacement actually executed. The matching artifacts are uploaded by the
# workflow's actions/upload-artifact step.
set -euo pipefail
ci_dir="${BASH_SOURCE[0]%/*}"
[[ "$ci_dir" != "${BASH_SOURCE[0]}" ]] || ci_dir=.
source "$ci_dir/lib.sh"
cd "$REPO_ROOT"

mkdir -p target/jankurai target/jankurai/security \
         target/jankurai/proofbind target/jankurai/proofmark

readonly protected_predecessor="de90586b48fbeafd1e3de8dd8d01e3cc348cda7f"
readonly protected_predecessor_tree="eb7cc72093faf3fb2f2d0420a58dc2c660ce913a"
readonly governed_cargo="/home/ubuntu/.rustup/toolchains/1.95.0-x86_64-unknown-linux-gnu/bin/cargo"
readonly governed_rustc="/home/ubuntu/.rustup/toolchains/1.95.0-x86_64-unknown-linux-gnu/bin/rustc"
readonly governed_llvm_cov="/home/ubuntu/.local/bin/cargo-llvm-cov"
readonly governed_mutants="/home/ubuntu/.cargo/bin/cargo-mutants"
readonly governed_mutants_version="cargo-mutants 25.3.1"

actual_predecessor_tree="$(/usr/bin/git rev-parse "$protected_predecessor^{tree}")"
if [[ "$actual_predecessor_tree" != "$protected_predecessor_tree" ]]; then
  printf '[ci] protected predecessor identity mismatch\n' >&2
  exit 1
fi

log "tool-adoption: fixed-predecessor diff ratchet"
/usr/bin/bash ops/ci/changed-fast-audit.sh \
  "$protected_predecessor" target/jankurai/diff
/usr/bin/jq -e \
  --arg base "$protected_predecessor" \
  '.base_ref == $base and (.changed_paths | length > 0)' \
  target/jankurai/diff/proof-plan.json >/dev/null

log "tool-adoption: full candidate audit"
run_governed_jankurai audit . --full --mode advisory \
  --policy agent/audit-policy.toml \
  --json target/jankurai/repo-score.json \
  --md target/jankurai/repo-score.md \
  --repair-queue-jsonl target/jankurai/repair-queue.jsonl \
  --no-score-history
/usr/bin/jq -e \
  '.score >= 85 and ((.hard_caps // []) | length == 0)
   and ([.findings[]? | select(.hardness == "hard")] | length == 0)' \
  target/jankurai/repo-score.json >/dev/null

# Exercise Proofbind and Proofmark in required mode over one shared, real Git
# change set. The fixture command is allowlisted by its own proof-lane map,
# executes an actual locked Rust test, and produces the contract receipt that
# joins the compiler coverage receipt.
readonly adoption_root="$REPO_ROOT/target/jankurai/adoption-fixture"
/usr/bin/rm -rf -- "$adoption_root"
/usr/bin/mkdir -p \
  "$adoption_root/agent" \
  "$adoption_root/src" \
  "$adoption_root/target/jankurai/proofbind" \
  "$adoption_root/target/jankurai/proofmark" \
  "$adoption_root/target/jankurai/proof-receipts"

/usr/bin/printf '/target/\n' >"$adoption_root/.gitignore"
/usr/bin/printf '%s\n' \
  '[package]' \
  'name = "proof-adoption-fixture"' \
  'version = "0.1.0"' \
  'edition = "2021"' \
  '' \
  '[workspace]' \
  >"$adoption_root/Cargo.toml"
/usr/bin/printf '%s\n' \
  '# This file is automatically @generated by Cargo.' \
  '# It is not intended for manual editing.' \
  'version = 4' \
  '' \
  '[[package]]' \
  'name = "proof-adoption-fixture"' \
  'version = "0.1.0"' \
  >"$adoption_root/Cargo.lock"
/usr/bin/printf '%s\n' \
  '{"workspace":"proof-adoption-fixture","owners":{"src/":"tools"}}' \
  >"$adoption_root/agent/owner-map.json"
fixture_command="CARGO=$governed_cargo CARGO_HOME=/home/ubuntu/.cargo RUSTC=$governed_rustc RUSTUP_HOME=/home/ubuntu/.rustup $governed_llvm_cov llvm-cov --manifest-path Cargo.toml --locked --offline --lcov --output-path target/jankurai/coverage.lcov"
/usr/bin/printf \
  '{"workspace":"proof-adoption-fixture","tests":{"src/":{"command":"%s","purpose":"real locked Rust contract test"}}}\n' \
  "$fixture_command" >"$adoption_root/agent/test-map.json"
/usr/bin/printf '%s\n' \
  '[[lane]]' \
  'name = "contract"' \
  "command = \"$fixture_command\"" \
  'purpose = "execute the real fixture contract test"' \
  'rules_covered = ["HLT-007-HANDWRITTEN-CONTRACT"]' \
  >"$adoption_root/agent/proof-lanes.toml"
/usr/bin/printf '%s\n' 'pub fn existing() -> bool { true }' >"$adoption_root/src/lib.rs"

/usr/bin/git -C "$adoption_root" init -q
/usr/bin/git -C "$adoption_root" add .gitignore Cargo.lock Cargo.toml agent src/lib.rs
/usr/bin/git -C "$adoption_root" \
  -c user.name='Jankurai Proof Adoption' \
  -c user.email='proof-adoption@example.invalid' \
  commit -q -m base

/usr/bin/printf '%s\n' \
  'pub fn existing() -> bool { true } pub fn added() -> bool { true } #[cfg(test)] mod tests { #[test] fn contracts_are_true() { assert!(super::existing()); assert!(super::added()); } }' \
  >"$adoption_root/src/lib.rs"
/usr/bin/git -C "$adoption_root" add src/lib.rs
/usr/bin/git -C "$adoption_root" \
  -c user.name='Jankurai Proof Adoption' \
  -c user.email='proof-adoption@example.invalid' \
  commit -q -m change
log "tool-adoption: execute typed contract receipt"
run_governed_jankurai prove "$adoption_root" --changed-from HEAD^ \
  --plan-out "$adoption_root/target/jankurai/proof-plan.json" \
  --plan-md "$adoption_root/target/jankurai/proof-plan.md" \
  --out-dir "$adoption_root/target/jankurai/proof-receipts" \
  --evidence-index "$adoption_root/target/jankurai/evidence-index.json"

if [[ "$("$governed_mutants" mutants --version)" != "$governed_mutants_version" ]]; then
  printf '[ci] governed cargo-mutants version mismatch\n' >&2
  exit 1
fi
fixture_source_sha256="$(/usr/bin/sha256sum "$adoption_root/src/lib.rs")"
fixture_source_sha256="${fixture_source_sha256%% *}"
log "tool-adoption: execute focused mutation proof"
(
  cd "$adoption_root"
  /usr/bin/env -i \
    CARGO_HOME=/home/ubuntu/.cargo \
    CARGO_NET_OFFLINE=true \
    GIT_CONFIG_GLOBAL=/dev/null \
    GIT_CONFIG_NOSYSTEM=1 \
    HOME=/nonexistent \
    LANG=C.UTF-8 \
    LC_ALL=C.UTF-8 \
    PATH=/home/ubuntu/.rustup/toolchains/1.95.0-x86_64-unknown-linux-gnu/bin:/usr/bin:/bin \
    RUSTUP_HOME=/home/ubuntu/.rustup \
    TZ=UTC \
    "$governed_mutants" mutants --in-place --no-shuffle --no-times \
      --colors never --annotations none --timeout 30 --file src/lib.rs \
      --output target/jankurai/mutants
)
fixture_source_sha256_after="$(/usr/bin/sha256sum "$adoption_root/src/lib.rs")"
fixture_source_sha256_after="${fixture_source_sha256_after%% *}"
if [[ "$fixture_source_sha256_after" != "$fixture_source_sha256" ]]; then
  printf '[ci] mutation proof did not restore the fixture source\n' >&2
  exit 1
fi
mutation_caught="$(/usr/bin/awk 'NF { count += 1 } END { print count + 0 }' \
  "$adoption_root/target/jankurai/mutants/mutants.out/caught.txt")"
mutation_missed="$(/usr/bin/awk 'NF { count += 1 } END { print count + 0 }' \
  "$adoption_root/target/jankurai/mutants/mutants.out/missed.txt")"
mutation_timeout="$(/usr/bin/awk 'NF { count += 1 } END { print count + 0 }' \
  "$adoption_root/target/jankurai/mutants/mutants.out/timeout.txt")"
mutation_unviable="$(/usr/bin/awk 'NF { count += 1 } END { print count + 0 }' \
  "$adoption_root/target/jankurai/mutants/mutants.out/unviable.txt")"
if [[ "$mutation_caught" -eq 0 || "$mutation_missed" -ne 0 ||
      "$mutation_timeout" -ne 0 || "$mutation_unviable" -ne 0 ]]; then
  printf '[ci] focused mutation proof is incomplete\n' >&2
  exit 1
fi
/usr/bin/jq -n \
  --argjson killed "$mutation_caught" \
  --argjson survived "$mutation_missed" \
  --argjson timeout "$mutation_timeout" \
  '{killed: $killed, survived: $survived, timeout: $timeout}' \
  >"$adoption_root/target/jankurai/mutation.json"

log "tool-adoption: proofbind obligations"
run_governed_jankurai proofbind verify "$adoption_root" \
  --changed-from HEAD^ \
  --mode advisory \
  --proof-receipts "$adoption_root/target/jankurai/proof-receipts" \
  --out "$adoption_root/target/jankurai/proofbind/surface-witness.json" \
  --obligations-out "$adoption_root/target/jankurai/proofbind/obligations.json" \
  --md "$adoption_root/target/jankurai/proofbind/proofbind.md"

log "tool-adoption: proofmark required"
run_governed_jankurai proofmark rust "$adoption_root" \
  --changed-from HEAD^ \
  --mode required \
  --obligations "$adoption_root/target/jankurai/proofbind/obligations.json" \
  --coverage "$adoption_root/target/jankurai/coverage.lcov" \
  --mutation "$adoption_root/target/jankurai/mutation.json" \
  --out "$adoption_root/target/jankurai/proofmark/proofmark-receipt.json" \
  --proof-receipt "$adoption_root/target/jankurai/proof-receipts/proofmark.json" \
  --md "$adoption_root/target/jankurai/proofmark/proofmark.md"

log "tool-adoption: proofbind required"
run_governed_jankurai proofbind verify "$adoption_root" \
  --changed-from HEAD^ \
  --mode required \
  --proof-receipts "$adoption_root/target/jankurai/proof-receipts" \
  --out target/jankurai/proofbind/surface-witness.json \
  --obligations-out target/jankurai/proofbind/obligations.json \
  --md target/jankurai/proofbind/proofbind.md

/usr/bin/cp \
  "$adoption_root/target/jankurai/proofmark/proofmark-receipt.json" \
  target/jankurai/proofmark/proofmark-receipt.json
/usr/bin/cp \
  "$adoption_root/target/jankurai/proof-receipts/proofmark.json" \
  target/jankurai/proofmark/proof-receipt.json

/usr/bin/jq -e \
  '.summary.total > 0
   and .summary.satisfied == .summary.total
   and .summary.missing == 0
   and .summary.high_or_critical_missing == 0
   and .summary.verdict == "pass"' \
  target/jankurai/proofbind/obligations.json >/dev/null
/usr/bin/jq -e \
  '.summary.total_obligations > 0
   and .summary.satisfied_obligations == .summary.total_obligations
   and .summary.review_obligations == 0
   and .summary.changed_units > 0
   and .coverage.status == "pass"
   and .summary.verdict == "pass"' \
  target/jankurai/proofmark/proofmark-receipt.json >/dev/null

# security: secret + dependency + SBOM/provenance evidence in one lane.
log "tool-adoption: security run"
run_governed_jankurai security run . \
  --script ops/ci/security.sh \
  --out target/jankurai/security/evidence.json
assert_artifact target/jankurai/security/evidence.json
